### PR TITLE
[WIP] Add lock around the execution of the callback.

### PR DESCRIPTION
**Pull request by congma**
If a callback is set, cache eviction is guarded by a lock. In this case,
because callback will be executed and it may execute arbitrary code --
which may include the dropping of the Python GIL, -- the cache may
become corrupted due to racing. The lock added in this commit ensures
that access to the state of the cache is synced even if the callback may
drop the GIL.

Ref: #22

### CODE REVIEW

**Comment by jamadden** [comment]
I suspect the [rotki developers/users](https://github.com/rotki/rotki/pull/2132) would be disappointed with this patch, because it does not cooperate with gevent or greenlets. I suspect they'd prefer to see a Python-level wrapper that uses the Python-level `threading.Lock`, since that can work with gevent/greenlets.

**Comment by congma** [comment]
@jamadden I have trouble understanding the underlying problem and I'd like to see an example. If the lack of support for concurrency I'm not sure if the module, as it currently is, can be modified in a fairly easy way. This fix here is more about prevent a hard crash that's very easy to trigger. There are many other issues with thread-safety to be resolved (for example, the fix as it stands now will reliably trigger a self-deadlock if during the callback the callback is called again).

**Comment by congma** [comment]
I'm converting this to a WIP, because I think as long as the callback mechanism exists, unsafe conditions (such as deadlock or inconsistency) can arise, and I need to think more about it.

**Comment by amitdev** [comment]
I'm not keen in adding any threading code in this library. Consumers concerned with thread safety can do one of the following approaches:
* Do not use the callback
* Add lightweight python wrapper outside this

**Comment by congma** [comment]
I've just done some basic critical-section protection in the codebase (not yet pushed). Essentially,

- All Python method calls on the LRU object appear as if atomic (protected by a mutex)
- Callback is in action only outside the critical section, so that even if it tries to modify the LRU itself or drop the GIL, the LRU's integrity is still protected. Unless the callback tries really hard (e.g. by forcefully grabbing the internal mutex via ctypes), it will not deadlock.

These changes will not make the LRU "concurrency-correct", in that different usage scenarios still call for different sorts of concurrency control that have to be implemented outside here. All it does is to make the object more resilient against crashes caused by internal state corruption. This will be relevant in single-thread code too, because the protection on internal states will reduce the chance that a callback may corrupt the LRU in a way that causes a crash.

I'll show my code in a different branch, and anyone interested may discuss there.

**Comment by congma** [comment]
This is closed in preference to #33. If anyone is interested, please discuss over there. Thank you very much.

**Pull request closed without merging**
