### PR TITLE
Feat: Add python stub

### PR DESCRIPTION
**Pull request by RF-Tar-Railt**
#49

### CODE REVIEW

**Comment by AndreMiras** [comment]
Hi @RF-Tar-Railt, would you mind rebasing this PR to master? Recent changes made it possible to run tests as part of the PR to prevent regressions, see https://github.com/amitdev/lru-dict/pull/54/files#r1359945835

**Comment by miili** [comment]
Where did the stubs go? Why were they reverted. IMO those are important in modern Python development.

**Comment by RF-Tar-Railt** [comment]
> Hi @RF-Tar-Railt, would you mind rebasing this PR to master? Recent changes made it possible to run tests as part of the PR to prevent regressions, see [#54 (files)](https://github.com/amitdev/lru-dict/pull/54/files#r1359945835)

updated.

**Comment by RF-Tar-Railt** [comment]
@amitdev  
All Build and Tests have passed.
image

**Please note that I did not modify the version**

**Comment by amitdev** [comment]
It seems to have some conflicts @RF-Tar-Railt

**Comment by RF-Tar-Railt** [comment]
> It seems to have some conflicts @RF-Tar-Railt

But I don't seem to have the authority to resolve conflicts

**Comment by amitdev** [comment]
Sorry, can you raise another PR? When I try to resolve conflict I get #56 which doesn't seem to include all changes?

**Comment by AndreMiras** [comment]
All we need is probably
```
git reset --hard origin/master
git cherry-pick d1ab20d8023b030dca9964aae056f9631f29d836
```

**Comment by RF-Tar-Railt** [comment]
> All we need is probably:
> ```
> git fetch --all
> git reset --hard origin/master
> git cherry-pick bf2faab891e0dae43108f14d875859ed995bf084
> git push --force
> ```
> This is assuming origin is `git@github.com:amitdev/lru-dict.git`, but depending on your setup/fork replace origin by upstream

use in my fork or ?

**Comment by AndreMiras** [comment]
Yes you can totally do it from your fork, say upstream is configured with `git@github.com:amitdev/lru-dict.git` and your fork is origin with `git@github.com:RF-Tar-Railt/lru-dict.git` you can:
```
git fetch --all
git reset --hard upstream/master # erase with master change
git cherry-pick bf2faab891e0dae43108f14d875859ed995bf084
git push --force
```

**Comment by RF-Tar-Railt** [comment]
done.

**Comment by AndreMiras** [comment]
Ahah I'm not sure why the PR closed though :sweat_smile:

**Comment by RF-Tar-Railt** [comment]
> Ahah I'm not sure why the PR closed though :sweat_smile:

#58 merged

**Pull request closed without merging**
